ComputerManager/ComputerManager/Models/ordercompuer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordercompuer
    {
        public int ocode { get; set; }
        public string sid { get; set; }
        public string comcode { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
    }
}

ComputerManager/ComputerManager/Controllers/OrdercompuersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ComputerManager.Models;

namespace ComputerManager.Controllers
{
    public class OrdercompuersController : Controller
    {
        private ComputerManagerDBEntities1 db = new ComputerManagerDBEntities1();

        // 订单列表
        public ActionResult Index()
        {
            return View(db.ordercompuer.ToList());
        }

        // 编辑订单
        public ActionResult Edit(string stu)
        {
            return View(db.ordercompuer.Find(stu));
        }
        //保存管理员
        public ActionResult Save(ordercompuer oc)
        {
            var dborder = db.ordercompuer.Find(oc.ocode);
            if(dborder!=null)
            {
                dborder.sid = oc.sid;
                dborder.comcode = oc.comcode;
                dborder.Start_Date = oc.Start_Date;
                dborder.End_Date = oc.End_Date;
                try
                {
                    db.SaveChanges();
                    return Content("<script>alert('修改成功！');window.history.back(-1);</script>");
                }
                catch(DbEntityValidationException ex)
                {
                    var errorMessages = ex.EntityValidationErrors
                        .SelectMany(x => x.ValidationErrors)
                        .Select(x => x.ErrorMessage);

                    string errorMessage = string.Join("; ", errorMessages);
                    return Content($"<script>alert('保存失败！错误信息：{errorMessage}');window.history.back(-1);</script>");

                }
            }
            else
            {
                db.ordercompuer.Add(oc);
                try
                {
                    db.SaveChanges();
                    return Content("<script>alert('新建成功！');window.history.back(-1);</script>");
                }
                catch(DbEntityValidationException ex)
                {
                    var errorMessages = ex.EntityValidationErrors
                        .SelectMany(x => x.ValidationErrors)
                        .Select(x => x.ErrorMessage);

                    string errorMessage = string.Join("; ", errorMessages);
                    return Content($"<script>alert('保存失败！错误信息：{errorMessage}');window.history.back(-1);</script>");

                }
            }
        }

        // 删除订单
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var rub = db.ordercompuer.FirstOrDefault(m => m.ocode == id);
            if(rub!=null)
            {
                db.ordercompuer.Remove(rub);
                db.SaveChanges();
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }

       
    }
}

ComputerManager/ComputerManager/Views/Ordercompuers/Create.cshtml
@model ComputerManager.Models.ordercompuer

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ordercompuer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.sid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.coid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.coid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.coid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Start_Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Start_Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Start_Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.End_Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.End_Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.End_Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ComputerManager/ComputerManager/Views/Ordercompuers/Delete.cshtml
@model ComputerManager.Models.ordercompuer

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ordercompuer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.sid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.coid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.coid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Start_Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Start_Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.End_Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.End_Date)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ComputerManager/ComputerManager/Views/Ordercompuers/Details.cshtml
@model ComputerManager.Models.ordercompuer

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>ordercompuer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.sid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.coid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.coid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Start_Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Start_Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.End_Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.End_Date)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ocode }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ComputerManager/ComputerManager/Views/Ordercompuers/Edit.cshtml
@model ComputerManager.Models.ordercompuer

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using ComputerManager.Models

<article class="cl pd-20">
    <form action="@Url.Action("Save")" method="post" class="form form-horizontal" id="form-member-add" style="margin-top:40px;margin-left:20px;">
        <div class="row cl">
            <label class="form-label col-xs-4 col-sm-3"><span class="c-red">*</span>订单号：</label>
            <div class="formControls col-xs-8 col-sm-9">
                @{
                    if (Model == null)
                    {


                        <input type="text" class="input-text" value="" placeholder="订单号"  id="ocode" name="ocode">
                    }
                    else
                    {
                        <input type="text" class="input-text" value="@Model.ocode" placeholder="@Model.ocode" readonly="readonly" id="ocode" name="ocode">
                    }
                }
            </div>
        </div>
        <div class="row cl">
            <label class="form-label col-xs-4 col-sm-3"><span class="c-red">*</span>学生学号：</label>
            <div class="formControls col-xs-8 col-sm-9">
                <input type="text" class="input-text" value="@Model.sid" placeholder="学生学号" id="sid" name="sid" readonly>
            </div>
        </div>
        <div class="row cl">
            <label class="form-label col-xs-4 col-sm-3"><span class="c-red">*</span>计算机号：</label>
            <div class="formControls col-xs-8 col-sm-9">
                <input type="text" class="input-text" value="" placeholder="计算机号" id="coid" name="coid">
            </div>
        </div>
        <div class="row cl">
            <label class="form-label col-xs-4 col-sm-3"><span class="c-red">*</span>开始时间：</label>
            <div class="formControls col-xs-8 col-sm-9">
                <input type="text" class="input-text" value="" placeholder="开始时间" id="Start_Date" name="Start_Date">
            </div>
        </div>
        <div class="row cl">
            <label class="form-label col-xs-4 col-sm-3"><span class="c-red">*</span>结束时间：</label>
            <div class="formControls col-xs-8 col-sm-9">
                <input type="text" class="input-text" value="" placeholder="结束时间" id="End_Date" name="End_Date">
            </div>
        </div>

        <div class="row cl">
            <div class="col-xs-8 col-sm-9 col-xs-offset-4 col-sm-offset-3">
                <input class="btn btn-primary radius" type="submit" value="&nbsp;&nbsp;提交&nbsp;&nbsp;">
            </div>
        </div>
    </form>
</article>

<script type="text/javascript">
    $(function () {
        $('.skin-minimal input').iCheck({
            checkboxClass: 'icheckbox-blue',
            radioClass: 'iradio-blue',
            increaseArea: '20%'
        });

        $("#form-member-add").validate({
            rules: {
                ocode: {
                    required: true,
                    minlength: 2,
                    maxlength: 16
                },
                sid: {
                    required: true,
                    minlength: 6,
                    maxlength: 16
                },
                coid: {
                    required: true,
                    minlength: 6,
                    maxlength: 16
                },
                Start_Date: {
                    required: true,
                },
                End_Date: {
                    required: true,
                },
            },
            onkeyup: false,
            focusCleanup: true,
            success: "valid",
            submitHandler: function (form) {
                var ocode = $("ocode").val();
                var sid = $("sid").val();
                var coid = $("coid").val();
                var Start_Date = $("Start_Date").val();
                var End_Date = $("End_Date").val();
                $(form).ajaxSubmit({
                    url: '@Url.Action("Save","Ordercompuers")',
                    type: 'POST',
                    data: {
                        comcode: comcode,
                        room: room,
                        cstate: cstate
                    },
                    success: function (result) {
                        if (result.success) {
                            layer.msg('保存成功!',{ icon: 1, time: 1000 }, function () {
                                window.location.href = '@Url.Action("Edit", "Ordercompuers")';
                            });
                        } else {
                            layer.msg('保存失败！',{ icon: 2, time: 1000 });
                        }
                    },
                    error: function () {
                        layer.msg('请求出错', { icon: 2, time: 1000 });
                    }
                });
            }
        });
    });

</script>

ComputerManager/ComputerManager/Views/Ordercompuers/Index.cshtml
@model IEnumerable<ComputerManager.Models.ordercompuer>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using ComputerManager.Models


<section class="Hui-article-box">
    <nav class="breadcrumb"><i class="Hui-iconfont">&#xe67f;</i> 首页 <span class="c-gray en">&gt;</span> 预定机房 <span class="c-gray en">&gt;</span> 预定机房<a class="btn btn-success radius r" style="line-height:1.6em;margin-top:3px" href="javascript:location.replace(location.href);" title="刷新"><i class="Hui-iconfont">&#xe68f;</i></a></nav>
    <div class="Hui-article">
        <article class="cl pd-20">
            <div class="text-c">
                <form action="" method="get">
                    日期范围：
                    <input type="text" onfocus="WdatePicker({maxDate:'#F{$dp.$D(\'datemax\')||\'%y-%M-%d\'}'})" id="datemin" class="input-text Wdate" style="width:120px;">
                    -
                    <input type="text" onfocus="WdatePicker({minDate:'#F{$dp.$D(\'datemin\')}',maxDate:'%y-%M-%d'})" id="datemax" class="input-text Wdate" style="width:120px;">
                    <input type="text" class="input-text" name="keyword" style="width:250px" value="@(Request.QueryString["keyword"]!= null ? Request.QueryString["keyword"] :"")" placeholder="输入管理员号、管理员姓名" id="" name="">
                    <button type="submit" class="btn btn-success radius" id="" name=""><i class="Hui-iconfont">&#xe665;</i> 搜订单</button>

                </form>
            </div>


            <div class="cl pd-5 bg-1 bk-gray mt-20">
                <span class="l">
                    <a href="javascript:;" onclick="datadel()" class="btn btn-danger radius"><i class="Hui-iconfont">&#xe6e2;</i> 批量删除</a>
                    <a href="javascript:void(0)" onclick="member_add('添加订单', '@Url.Action("Edit")', '510', '600')" class="btn btn-primary radius"><i class="Hui-iconfont">&#xe600;</i> 添加订单</a>
                </span>
            </div>
            <div class="mt-20">
                <table class="table table-border table-bordered table-hover table-bg table-sort">
                    <thead>
                        <tr class="text-c">
                            <th width="25"><input type="checkbox" name="" value=""></th>
                            <th width="100">订单编号</th>
                            <th width="70">学生学号</th>
                            <th width="70">计算机编号</th>
                            <th width="100">开始时间</th>
                            <th width="100">结束时间</th>
                            <th width="100">操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (ordercompuer item in Model)
                        {
                            <tr class="text-c">
                                <td><input type="checkbox" value="1" name=""></td>
                                <td>@item.ocode</td>
                                <td>@item.sid</td>
                                <td>@item.coid</td>
                                <td>@item.Start_Date</td>
                                <td>@item.End_Date</td>

                                <td class="td-manage">
                                    <a title="编辑" href="javascript:void(0)" onclick="member_edit('编辑', '@Url.Action("Edit", new { Id = item.ocode })', '4', '510', '600')" class="ml-5" style="text-decoration:none"><i class="Hui-iconfont">&#xe6df;</i></a>
                                    <a title="删除" href="javascript:void(0);" onclick="member_del(this, '@item.ocode')" class="ml-5" style="text-decoration:none"><i class="Hui-iconfont">&#xe6e2;</i></a>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </article>
    </div>
</section>

<script type="text/javascript">
    $(function () {
        $('.table-sort').dataTable({
            "aaSorting": [[1, "desc"]],//默认第几个排序
            "bStateSave": true,//状态保存
            "aoColumnDefs": [
                //{"bVisible": false, "aTargets": [ 3 ]} //控制列的隐藏显示
                { "orderable": false, "aTargets": [0, 8, 9] }// 制定列不参与排序
            ]
        });
        $('.table-sort tbody').on('click', 'tr', function () {
            if ($(this).hasClass('selected')) {
                $(this).removeClass('selected');
            }
            else {
                table.$('tr.selected').removeClass('selected');
                $(this).addClass('selected');
            }
        });
    });
    /*用户-添加*/
    function member_add(title, url, w, h) {
        layer_show(title, url, w, h);
    }
    /*用户-查看*/
    function member_show(title, url, id, w, h) {
        layer_show(title, url, w, h);
    }
    /*用户-编辑*/
    function member_edit(title, url, id, w, h) {
        event.preventDefault(); // 阻止事件的默认行为
        event.stopPropagation(); // 阻止事件的冒泡

        layer.open({
            type: 2,
            title: title,
            area: [w + 'px', h + 'px'],
            shadeClose: false, // 禁用点击弹窗外部关闭弹窗的功能
            content: url
        });
    }

     /*用户-删除*/
    function member_del(obj, id) {
        layer.confirm('确认要删除吗？', function (index) {
            $.ajax({
                url: '@Url.Action("Delete")? Id=id',
                type: 'POST',
                data: { id: id },
                success: function (result) {
                    if (result.success) {
                        $(obj).parents("tr").remove();
                        layer.msg('已删除!', { icon: 1, time: 1000 });
                    } else {
                        //处理删除失败的情况
                        layer.msg('删除失败', { icon: 2, time: 1000 });
                    }
                },
                error: function () {
                    //处理请求出错的情况
                    layer.msg('请求出错！', { icon: 2, time: 1000 });
                }
            });

        });
    }
</script>