ComputerManager/ComputerManager/Controllers/SelectComputers1Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Timers;
using ComputerManager.Models;

namespace ComputerManager.Controllers
{
    public class SelectComputers1Controller : Controller
    {
        private ComputerManagerDBEntities1 db = new ComputerManagerDBEntities1();
        private Timer orderTimer;

        // 计算机列表
        public ActionResult Index()
        {
            return View(db.computer.ToList());
        }

        //初始化定时器
        public SelectComputers1Controller()
        {
            orderTimer = new Timer();
            orderTimer.Interval = 3600000; // 1小时
            orderTimer.Elapsed += OrderTimer_Elapsed;
            orderTimer.AutoReset = true;
            orderTimer.Start();
        }

        //定时任务，设置状态
        private void OrderTimer_Elapsed(object sender, ElapsedEventArgs e)
        {
            //定时任务，处理订单超时逻辑
            var orders = db.ordercompuer.ToList();
            var currentTime = DateTime.Now;
            foreach(var ord in orders)
            {
                //检查订单是否超时
                if(ord.End_Date<=currentTime)
                {
                    //更新计算机状态为0
                    var com = db.computer.FirstOrDefault(c => c.comcode == ord.comcode);
                    if(com!=null)
                    {
                        com.cstate = "0";
                    }
                    //订单表中删除该订单
                    db.ordercompuer.Remove(ord);
                }
            }
            db.SaveChanges();
        }

        // 编辑计算机
        public ActionResult Edit(string sid, string cid)
        {
            return View(db.ordercompuer.FirstOrDefault(o => o.sid == sid && o.comcode == cid));
        }


        // 保存编辑
        [HttpPost]
        public ActionResult Save(ordercompuer ocm)
        {
            var com = db.computer.Find(ocm.comcode);
            if (com != null && com.cstate.Trim() == "0")
            {
                // 新建订单
                var order = new ordercompuer
                {
                    sid = ocm.sid,
                    comcode = ocm.comcode,
                    Start_Date = DateTime.Now,
                    End_Date = DateTime.Now.AddHours(1)
                };
                db.ordercompuer.Add(order);
                db.SaveChanges();

                // 设置计算机状态为1
                com.cstate = "1";
                db.SaveChanges();

                // 启动定时器
                orderTimer.Start();

                return Content("<script>alert('新建成功！');window.history.back(-1);</script>");
            }
            else if (com != null && com.cstate.Trim() == "1")
            {
                // 修改订单时间为1小时
                var order = db.ordercompuer.FirstOrDefault(o => o.sid == ocm.sid && o.comcode == ocm.comcode);
                if (order != null)
                {
                    order.Start_Date = DateTime.Now;
                    order.End_Date = DateTime.Now.AddHours(1);
                }

                db.SaveChanges();

                // 启动定时器
                orderTimer.Start();

                return Content("<script>alert('修改成功！');window.history.back(-1);</script>");
            }
            else
            {
                return Content("<script>alert('无法进行新建订单！');window.history.back(-1);</script>");
            }
        }

    }
}

ComputerManager/ComputerManager/Views/SelectComputers1/Create.cshtml
@model ComputerManager.Models.computer

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>computer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.room, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.room, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.room, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.comcode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.comcode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.comcode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cstate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cstate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cstate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ComputerManager/ComputerManager/Views/SelectComputers1/Delete.cshtml
@model ComputerManager.Models.computer

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>computer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.room)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.room)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cstate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cstate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ComputerManager/ComputerManager/Views/SelectComputers1/Details.cshtml
@model ComputerManager.Models.computer

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>computer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.room)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.room)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cstate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cstate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.comcode }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ComputerManager/ComputerManager/Views/SelectComputers1/Edit.cshtml
@model ComputerManager.Models.computer

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using ComputerManager.Models

<article class="cl pd-20">
    <form action="@Url.Action("Save")" method="post" class="form form-horizontal" id="form-member-add" style="margin-top:40px;margin-left:20px;">
        <div class="row cl">
            <label class="form-label col-xs-4 col-sm-3"><span class="c-red">*</span>学号：</label>
            <div class="formControls col-xs-8 col-sm-9">
                <input type="text" class="input-text" value="@Session["stuInfo"]" placeholder="@Session["stuInfo"]" readonly="readonly" id="sid" name="sid">
            </div>
        </div>
        <div class="row cl">
            <label class="form-label col-xs-4 col-sm-3"><span class="c-red">*</span>计算机号：</label>
            <div class="formControls col-xs-8 col-sm-9">
                <input type="text" class="input-text" value="" placeholder="计算机号"  id="comcode" name="comcode">
            </div>
        </div>
        <div class="row cl">
            <div class="col-xs-8 col-sm-9 col-xs-offset-4 col-sm-offset-3">
                <input class="btn btn-primary radius" type="submit" value="&nbsp;&nbsp;提交&nbsp;&nbsp;">
            </div>
        </div>
    </form>
</article>

<script type="text/javascript">
    $(function () {
        $('.skin-minimal input').iCheck({
            checkboxClass: 'icheckbox-blue',
            radioClass: 'iradio-blue',
            increaseArea: '20%'
        });

        $("#form-member-add").validate({
            rules: {
                sid:{
                    required: true,
                },
                comcode: {
                    required: true,
                },
            },
            onkeyup: false,
            focusCleanup: true,
            success: "valid",
            submitHandler: function (form) {
                var comcode = $("comcode").val();
                var room = $("room").val();
                var cstate = $("input[name='cstate']:checked").val();
                $(form).ajaxSubmit({
                    url: '@Url.Action("Save", "SelectComputers1")',
                    type: 'POST',
                    data: {
                        comcode: comcode,
                        sid: sid,
                    },
                    success: function (result) {
                        if (result.success) {
                            layer.msg('保存成功!',{ icon: 1, time: 1000 }, function () {
                                window.location.href = '@Url.Action("Edit", "SelectComputers1")';
                            });
                        } else {
                            layer.msg('保存失败！',{ icon: 2, time: 1000 });
                        }
                    },
                    error: function () {
                        layer.msg('请求出错', { icon: 2, time: 1000 });
                    }
                });
            }
        });
    });

</script>

ComputerManager/ComputerManager/Views/SelectComputers1/Index.cshtml
@model IEnumerable<ComputerManager.Models.computer>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using ComputerManager.Models

<section class="Hui-article-box">
    <nav class="breadcrumb"><i class="Hui-iconfont">&#xe67f;</i> 首页 <span class="c-gray en">&gt;</span> 预定机房 <span class="c-gray en">&gt;</span> 预定机房<a class="btn btn-success radius r" style="line-height:1.6em;margin-top:3px" href="javascript:location.replace(location.href);" title="刷新"><i class="Hui-iconfont">&#xe68f;</i></a></nav>
    <div class="Hui-article">
        <article class="cl pd-20">
            <div class="text-c">
                <form action="" method="get">
                    日期范围：
                    <input type="text" onfocus="WdatePicker({maxDate:'#F{$dp.$D(\'datemax\')||\'%y-%M-%d\'}'})" id="datemin" class="input-text Wdate" style="width:120px;">
                    -
                    <input type="text" onfocus="WdatePicker({minDate:'#F{$dp.$D(\'datemin\')}',maxDate:'%y-%M-%d'})" id="datemax" class="input-text Wdate" style="width:120px;">
                    <input type="text" class="input-text" name="keyword" style="width:250px" value="@(Request.QueryString["keyword"]!= null ? Request.QueryString["keyword"] :"")" placeholder="输入计算机编号、机房号" id="" name="">
                    <button type="submit" class="btn btn-success radius" id="" name=""><i class="Hui-iconfont">&#xe665;</i> 搜计算机</button>

                </form>
            </div>

            <div class="cl pd-5 bg-1 bk-gray mt-20">
                <span class="l">
                    <a href="javascript:void(0)" onclick="member_add('添加计算机', '@Url.Action("Edit")', '510', '600')" class="btn btn-primary radius"><i class="Hui-iconfont">&#xe600;</i> 添加计算机</a>
                </span>
            </div>
            <div class="mt-20">
                <table class="table table-border table-bordered table-hover table-bg table-sort">
                    <thead>
                        <tr class="text-c">
                            <th width="25"><input type="checkbox" name="" value=""></th>
                            <th width="100">计算机编号</th>
                            <th width="70">机房号</th>
                            <th width="70">状态</th>
                            <th width="100">操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (computer item in Model)
                        {
                            <tr class="text-c">
                                <td><input type="checkbox" value="1" name=""></td>
                                <td>@item.comcode</td>
                                <td>@item.room</td>
                                @{
                                    if (@item.cstate.Trim() == "0")
                                    {
                                        <td class="td-status"><span class="label label-success radius">@item.cstate</span></td>
                                    }
                                    else
                                    {
                                        <td class="td-status"><span class="label label-defaunt radius">@item.cstate</span></td>
                                    }
                                }

                                <td class="td-manage">
                                    <a title="编辑" href="javascript:void(0)" onclick="member_edit('编辑', '@Url.Action("Edit", new { Id = item.comcode })', '4', '510', '600')" class="ml-5" style="text-decoration:none"><i class="Hui-iconfont">&#xe6df;</i></a>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </article>
    </div>
</section>

<script type="text/javascript">
    $(function () {
        $('.table-sort').dataTable({
            "aaSorting": [[1, "desc"]],//默认第几个排序
            "bStateSave": true,//状态保存
            "aoColumnDefs": [
                //{"bVisible": false, "aTargets": [ 3 ]} //控制列的隐藏显示
                { "orderable": false, "aTargets": [0, 8, 9] }// 制定列不参与排序
            ]
        });
        $('.table-sort tbody').on('click', 'tr', function () {
            if ($(this).hasClass('selected')) {
                $(this).removeClass('selected');
            }
            else {
                table.$('tr.selected').removeClass('selected');
                $(this).addClass('selected');
            }
        });
    });
    /*用户-添加*/
    function member_add(title, url, w, h) {
        layer_show(title, url, w, h);
    }
    /*用户-查看*/
    function member_show(title, url, id, w, h) {
        layer_show(title, url, w, h);
    }
    /*用户-编辑*/
    function member_edit(title, url, id, w, h) {
        event.preventDefault(); // 阻止事件的默认行为
        event.stopPropagation(); // 阻止事件的冒泡

        layer.open({
            type: 2,
            title: title,
            area: [w + 'px', h + 'px'],
            shadeClose: false, // 禁用点击弹窗外部关闭弹窗的功能
            content: url
        });
    }
</script>