ComputerManager/Models/computer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class computer
    {
        public string room { get; set; }
        public string comcode { get; set; }
        public string cstate { get; set; }
    }
}

ComputerManager/Controllers/ComputersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ComputerManager.Models;

namespace ComputerManager.Controllers
{
    //计算机控制器
    public class ComputersController : Controller
    {
        private ComputerManagerDBEntities1 db = new ComputerManagerDBEntities1();

        // 计算机列表

        public ActionResult Index()
        {
            return View(db.computer.ToList());
        }


        // 编辑计算机
        public ActionResult Edit(string id)
        {
            return View(db.computer.Find(id));
        }

        // 保存编辑
        [HttpPost]
        public ActionResult Save(computer com)
        {
            var dbcomputer = db.computer.Find(com.comcode);
            if (dbcomputer != null)
            {
                dbcomputer.room = com.room;
                dbcomputer.cstate = com.cstate;
                db.SaveChanges();
                return Content("<script>alert('修改成功！');window.history.back(-1);</script>");
            }
            else
            {
                db.computer.Add(com);
                db.SaveChanges();
                return Content("<script>alert('新建成功！');window.history.back(-1);</script>");
            }
        }

        [HttpPost]
        public ActionResult Delete(string id)
        {
            var rub = db.computer.FirstOrDefault(m => m.comcode == id);
            if (rub != null)
            {
                db.computer.Remove(rub);
                db.SaveChanges();
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }
        [HttpPost]
        public ActionResult ChangeStatus(string id)
        {
            computer rub = db.computer.FirstOrDefault(m => m.comcode == id);
            if (rub != null)
            {
                if (rub.cstate.Trim() == "0")
                {
                    rub.cstate = "1";
                    db.SaveChanges();
                    return Json(new { success = true });
                }
                else if(rub.cstate.Trim()=="1")
                {
                    rub.cstate = "0";
                    db.SaveChanges();
                    return Json(new { success = true });
                }
                                
            }
            return Json(new { success = false });
        }


    }
}

ComputerManager/Views/Computers/Create.cshtml
@model ComputerManager.Models.computer

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>computer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.room, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.room, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.room, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.comcode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.comcode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.comcode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cstate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cstate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cstate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ComputerManager/Views/Computers/Delete.cshtml
@model ComputerManager.Models.computer

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>computer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.room)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.room)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cstate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cstate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ComputerManager/Views/Computers/Details.cshtml
@model ComputerManager.Models.computer

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>computer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.room)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.room)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cstate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cstate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.comcode }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ComputerManager/Views/Computers/Edit.cshtml
@model ComputerManager.Models.computer

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using ComputerManager.Models

<article class="cl pd-20">
    <form action="@Url.Action("Save")" method="post" class="form form-horizontal" id="form-member-add" style="margin-top:40px;margin-left:20px;">
        <div class="row cl">
            <label class="form-label col-xs-4 col-sm-3"><span class="c-red">*</span>计算机号：</label>
            <div class="formControls col-xs-8 col-sm-9">
                @{
                    if (Model == null)
                    {


                        <input type="text" class="input-text" value="" placeholder="计算机号" id="comcode" name="comcode">
                    }
                    else
                    {
                        <input type="text" class="input-text" value="@Model.comcode" placeholder="计算机号" readonly="readonly" id="comcode" name="comcode">
                    }
                }
            </div>
        </div>
        <div class="row cl">
            <label class="form-label col-xs-4 col-sm-3"><span class="c-red">*</span>计算机房号：</label>
            <div class="formControls col-xs-8 col-sm-9">
                <input type="text" class="input-text" value="" placeholder="计算机房号" id="room" name="room">
            </div>
        </div>
        <div class="row cl">
            <label class="form-label col-xs-4 col-sm-3"><span class="c-red">*</span>计算机状态：</label>
            <div class="formControls col-xs-8 col-sm-9 skin-minimal">
                <div class="radio-box">
                    <input name="cstate" type="radio" id="cstate-1" value="0" checked>
                    <label for="cstate-1">启用</label>
                </div>
                <div class="radio-box">
                    <input type="radio" id="cstate-2" value="1" name="cstate">
                    <label for="cstate-2">禁用</label>
                </div>
            </div>
        </div>

        <div class="row cl">
            <div class="col-xs-8 col-sm-9 col-xs-offset-4 col-sm-offset-3">
                <input class="btn btn-primary radius" type="submit" value="&nbsp;&nbsp;提交&nbsp;&nbsp;">
            </div>
        </div>
    </form>
</article>

<script type="text/javascript">
    $(function () {
        $('.skin-minimal input').iCheck({
            checkboxClass: 'icheckbox-blue',
            radioClass: 'iradio-blue',
            increaseArea: '20%'
        });

        $("#form-member-add").validate({
            rules: {
                room: {
                    required: true,
                    minlength: 2,
                    maxlength: 16
                },
                comcode: {
                    required: true,
                    minlength: 6,
                    maxlength: 16
                },
                cstate: {
                    required: true,
                },
            },
            onkeyup: false,
            focusCleanup: true,
            success: "valid",
            submitHandler: function (form) {
                var comcode = $("comcode").val();
                var room = $("room").val();
                var cstate = $("input[name='cstate']:checked").val();
                $(form).ajaxSubmit({
                    url: '@Url.Action("Save","Computers")',
                    type: 'POST',
                    data: {
                        comcode: comcode,
                        room: room,
                        cstate: cstate
                    },
                    success: function (result) {
                        if (result.success) {
                            layer.msg('保存成功!',{ icon: 1, time: 1000 }, function () {
                                window.location.href = '@Url.Action("Edit","Computers")';
                            });
                        } else {
                            layer.msg('保存失败！',{ icon: 2, time: 1000 });
                        }
                    },
                    error: function () {
                        layer.msg('请求出错', { icon: 2, time: 1000 });
                    }
                });
            }
        });
    });

</script>

ComputerManager/Views/Computers/Index.cshtml
@model IEnumerable<ComputerManager.Models.computer>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using ComputerManager.Models

<section class="Hui-article-box">
    <nav class="breadcrumb"><i class="Hui-iconfont">&#xe67f;</i> 首页 <span class="c-gray en">&gt;</span> 机房管理 <span class="c-gray en">&gt;</span> 计算机列表<a class="btn btn-success radius r" style="line-height:1.6em;margin-top:3px" href="javascript:location.replace(location.href);" title="刷新"><i class="Hui-iconfont">&#xe68f;</i></a></nav>
    <div class="Hui-article">
        <article class="cl pd-20">
            <div class="text-c">
                <form action="" method="get">
                    日期范围：
                    <input type="text" onfocus="WdatePicker({maxDate:'#F{$dp.$D(\'datemax\')||\'%y-%M-%d\'}'})" id="datemin" class="input-text Wdate" style="width:120px;">
                    -
                    <input type="text" onfocus="WdatePicker({minDate:'#F{$dp.$D(\'datemin\')}',maxDate:'%y-%M-%d'})" id="datemax" class="input-text Wdate" style="width:120px;">
                    <input type="text" class="input-text" name="keyword" style="width:250px" value="@(Request.QueryString["keyword"]!= null ? Request.QueryString["keyword"] :"")" placeholder="输入计算机编号、机房号" id="" name="">
                    <button type="submit" class="btn btn-success radius" id="" name=""><i class="Hui-iconfont">&#xe665;</i> 搜计算机</button>

                </form>
            </div>
            
            <div class="cl pd-5 bg-1 bk-gray mt-20"> <span class="l"><a href="javascript:;" onclick="datadel()" class="btn btn-danger radius"><i class="Hui-iconfont">&#xe6e2;</i> 批量删除</a> 
                <a href="javascript:void(0)" onclick="member_add('添加计算机', '@Url.Action("Edit")', '510', '600')" class="btn btn-primary radius"><i class="Hui-iconfont">&#xe600;</i> 添加计算机</a></div>
            <div class="mt-20">
                <table class="table table-border table-bordered table-hover table-bg table-sort">
                    <thead>
                        <tr class="text-c">
                            <th width="25"><input type="checkbox" name="" value=""></th>
                            <th width="100">计算机编号</th>
                            <th width="70">机房号</th>
                            <th width="70">状态</th>
                            <th width="100">操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (computer item in Model)
                        {
                        <tr class="text-c">
                            <td><input type="checkbox" value="1" name=""></td>
                            <td>@item.comcode</td>
                            <td>@item.room</td>
                            @{
                                if (@item.cstate.Trim() == "0")
                                {
                                    <td class="td-status"><span class="label label-success radius">@item.cstate</span></td>
                                }
                                else
                                {
                                    <td class="td-status"><span class="label label-defaunt radius">@item.cstate</span></td>
                                }
                            }


                            <td class="td-manage">
                                <a style="text-decoration:none" onClick="member_stop(this, '10001', '@item.comcode')" href="javascript:;" title="停用"><i class="Hui-iconfont">&#xe631;</i></a>
                                <a title="编辑" href="javascript:void(0)" onclick="member_edit('编辑', '@Url.Action("Edit", new { Id = item.comcode })', '4', '510', '600')" class="ml-5" style="text-decoration:none"><i class="Hui-iconfont">&#xe6df;</i></a>
                                <a title="删除" href="javascript:void(0);" onclick="member_del(this,'@item.comcode')" class="ml-5" style="text-decoration:none"><i class="Hui-iconfont">&#xe6e2;</i></a>
                            </td>
                        </tr>
                        }

                    </tbody>
                </table>
            </div>
        </article>
    </div>
</section>

<script type="text/javascript">
    $(function () {
        $('.table-sort').dataTable({
            "aaSorting": [[1, "desc"]],//默认第几个排序
            "bStateSave": true,//状态保存
            "aoColumnDefs": [
                //{"bVisible": false, "aTargets": [ 3 ]} //控制列的隐藏显示
                { "orderable": false, "aTargets": [0, 8, 9] }// 制定列不参与排序
            ]
        });
        $('.table-sort tbody').on('click', 'tr', function () {
            if ($(this).hasClass('selected')) {
                $(this).removeClass('selected');
            }
            else {
                table.$('tr.selected').removeClass('selected');
                $(this).addClass('selected');
            }
        });
    });
    /*用户-添加*/
    function member_add(title, url, w, h) {
        layer_show(title, url, w, h);
    }
    /*用户-查看*/
    function member_show(title, url, id, w, h) {
        layer_show(title, url, w, h);
    }
 /*用户-停用*/
    function member_stop(obj, id,x) {
        layer.confirm('确认要改变使用状态吗？', function (index) {
            $.ajax({
                url: '@Url.Action("ChangeStatus")? Id=id',
                type: 'POST',
                data: { id: x },
                success: function (result) {
                    if (result.success) {
                        $(obj).parents("tr").find(".td-manage").prepend('<a style="text-decoration:none" onClick="member_start(this,id)" href="javascript:;" title="启用"><i class="Hui-iconfont">&#xe6e1;</i></a >');
                        $(obj).parents("tr").find(".td-status").html('<span class="label label-defaunt radius">1</span>');
                        $(obj).remove();
                        layer.msg('已停用!', { icon: 5, time: 1000 });
                    } else {
                        layer.msg('停用失败!', { icon: 2, time: 1000 });
                    }
                },
                error: function () {
                    layer.msg('请求出错！', { icon: 2, time: 1000 });
                }
            });
            layer.close(index);
        });
    }

/*用户-启用*/
    function member_start(obj, id,x) {
        layer.confirm('确认要启用吗？', function (index) {
            $.ajax({
                url: '@Url.Action("ChangeStatus")? Id=id',
                type: 'POST',
                data: { id: x },
                success: function (result) {
                    if (result.success) {
                        $(obj).parents("tr").find(".td-manage").prepend('<a style="text-decoration:none" onClick="member_stop(this,id)" href="javascript:;" title="停用"><i class="Hui-iconfont">&#xe631;</i></a >');
                        $(obj).parents("tr").find(".td-status").html('<span class="label label-success radius">0</span>');
                        $(obj).remove();
                        layer.msg('已启用!', { icon: 6, time: 1000 });
                    } else {
                        layer.msg('启用失败!', { icon: 2, time: 1000 });
                    }
                },
                error: function () {
                    layer.msg('请求出错！', { icon: 2, time: 1000 });
                }
            });
            layer.close(index);
        });
    }

    /*用户-编辑*/
    function member_edit(title, url, id, w, h) {
        event.preventDefault(); // 阻止事件的默认行为
        event.stopPropagation(); // 阻止事件的冒泡

        layer.open({
            type: 2,
            title: title,
            area: [w + 'px', h + 'px'],
            shadeClose: false, // 禁用点击弹窗外部关闭弹窗的功能
            content: url
        });
    }
    /*用户-删除*/
    function member_del(obj, id) {
        layer.confirm('确认要删除吗？', function (index) {
            $.ajax({
                url: '@Url.Action("Delete")? Id=id',
                type: 'POST',
                data: { id: id },
                success: function (result) {
                    if (result.success) {
                        $(obj).parents("tr").remove();
                        layer.msg('已删除!', { icon: 1, time: 1000 });
                    } else {
                        //处理删除失败的情况
                        layer.msg('删除失败', { icon: 2, time: 1000 });
                    }
                },
                error: function () {
                    //处理请求出错的情况
                    layer.msg('请求出错！', { icon: 2, time: 1000 });
                }
            });

        });
    }
</script>